apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app.kubernetes.io/created-by: eks-hackathon-2023
    app.kubernetes.io/type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/instance: orders
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/instance: orders
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: eks-hackathon-2023
    spec:
      containers:
        - name: orders
          env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
            - name: SPRING_DATASOURCE_WRITER_URL
              valueFrom:
                secretKeyRef:
                 #url?
            - name: SPRING_DATASOURCE_WRITER_USERNAME
              valueFrom:
                secretKeyRef:
            - name: SPRING_DATASOURCE_WRITER_PASSWORD
              valueFrom:
            - name: SPRING_DATASOURCE_READER_URL
              valueFrom:
                  key: url
            SPRING_DATASOURCE_READER_USERNAME
              
            SPRING_DATASOURCE_READER_PASSWORD
              
          envFrom:
            - configMapRef:
                name: orders
          image: ""
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            successThreshold: 3
            periodSeconds: 5
            resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      #nodeSelector:
        #nodo: app
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
