apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: checkout
  labels:
    app.kubernetes.io/created-by: eks-hackathon-2023
spec:
  type: ClusterIP
  ports:
    - port: 
      name: http
  selector:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/component: service
