apiVersion: v1
kind: Service
metadata:
  name: carts-dynamodb
  namespace: carts
  labels:
    app.kubernetes.io/created-by: eks-hackathon-2023
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: dynamodb
      protocol: TCP
      name: dynamodb
  selector:
    app.kubernetes.io/name: carts
    app.kubernetes.io/instance: carts
    app.kubernetes.io/component: dynamodb
