apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
  namespace: assets
  labels:
    app.kubernetes.io/created-by: eks-hackathon-2023
    app.kubernetes.io/type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: assets
      app.kubernetes.io/instance: assets
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: assets
        app.kubernetes.io/instance: assets
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: eks-hackathon-2023
    spec:
      containers:
        - name: assets
          envFrom:
            - configMapRef:
                name: assets
          image: ""
          imagePullPolicy: IfNotPresent
          #???? 
