apiVersion: v1
kind: Service
metadata:
  name: assets
  namespace: assets
  labels:
    app.kubernetes.io/created-by: eks-hackathon-2023
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    #app.kubernetes.io/name: 
    #app.kubernetes.io/instance: 
    #app.kubernetes.io/component: 
